export const data = JSON.parse("{\"key\":\"v-769cf21f\",\"path\":\"/Userdocs/nas/mount.html\",\"title\":\"NAS的使用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"NAS的使用\",\"order\":1,\"author\":\"fengjk\",\"date\":\"2023-09-01T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"使用技巧\",\"NAS存储\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"按照之前说的功能，本文将会介绍不同终端如何挂载和使用nas。 类似大U盘，他的目录如下： nas里有两个目录：public，`resource。- public目录为每个人存放数据的目录，用使用拼音命名； resource目录为存放数据集的目录，方便大家公用数据集；; 注：private目录因为权限问题已经移除（可能以后会添加回来）。 ==容器端（必读...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/Userdocs/nas/mount.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"NAS的使用\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"按照之前说的功能，本文将会介绍不同终端如何挂载和使用nas。 类似大U盘，他的目录如下： nas里有两个目录：public，`resource。- public目录为每个人存放数据的目录，用使用拼音命名； resource目录为存放数据集的目录，方便大家公用数据集；; 注：private目录因为权限问题已经移除（可能以后会添加回来）。 ==容器端（必读...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"http://liandan.cn:8080/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"NAS的使用\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"使用技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"NAS存储\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-09-01T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"NAS的使用\\\",\\\"image\\\":[\\\"http://liandan.cn:8080/\\\"],\\\"datePublished\\\":\\\"2023-09-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"容器端（必读、重点）\",\"slug\":\"容器端-必读、重点\",\"link\":\"#容器端-必读、重点\",\"children\":[]},{\"level\":2,\"title\":\"网页端\",\"slug\":\"网页端\",\"link\":\"#网页端\",\"children\":[]},{\"level\":2,\"title\":\"Windows端\",\"slug\":\"windows端\",\"link\":\"#windows端\",\"children\":[]},{\"level\":2,\"title\":\"手机端\",\"slug\":\"手机端\",\"link\":\"#手机端\",\"children\":[]},{\"level\":2,\"title\":\"mac端\",\"slug\":\"mac端\",\"link\":\"#mac端\",\"children\":[]},{\"level\":2,\"title\":\"ubuntu端\",\"slug\":\"ubuntu端\",\"link\":\"#ubuntu端\",\"children\":[]}],\"readingTime\":{\"minutes\":2.55,\"words\":765},\"filePathRelative\":\"Userdocs/nas/mount.md\",\"localizedDate\":\"2023年9月1日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
