export const data = JSON.parse("{\"key\":\"v-96e51f0a\",\"path\":\"/GPUdocs/user/fast/network.html\",\"title\":\"容器网络配置\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"容器网络配置\",\"order\":2,\"author\":\"fengjk\",\"date\":\"2023-08-31T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"使用技巧\",\"快速开始\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"两地网络状况 链数服务器 链数服务器可以直接上网，但是对于安装国外软件较慢的情况，我们提供了一些解决方案，通过代理加速外国资源访问。 校内服务器 校内服务器无法直接上网，只能正确配置代理之后才能上网。 我们使用上网方式，称为“代理”或者“代理上网”。 代理上网原理 现状：我们需要访问网站Web https://google.com:443 机器A（服务...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/GPUdocs/user/fast/network.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"容器网络配置\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"两地网络状况 链数服务器 链数服务器可以直接上网，但是对于安装国外软件较慢的情况，我们提供了一些解决方案，通过代理加速外国资源访问。 校内服务器 校内服务器无法直接上网，只能正确配置代理之后才能上网。 我们使用上网方式，称为“代理”或者“代理上网”。 代理上网原理 现状：我们需要访问网站Web https://google.com:443 机器A（服务...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"使用技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"快速开始\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-08-31T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"容器网络配置\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-08-31T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"两地网络状况\",\"slug\":\"两地网络状况\",\"link\":\"#两地网络状况\",\"children\":[]},{\"level\":2,\"title\":\"代理上网\",\"slug\":\"代理上网\",\"link\":\"#代理上网\",\"children\":[{\"level\":3,\"title\":\"1. 国内资源访问\",\"slug\":\"_1-国内资源访问\",\"link\":\"#_1-国内资源访问\",\"children\":[]},{\"level\":3,\"title\":\"2. 国外资源加速\",\"slug\":\"_2-国外资源加速\",\"link\":\"#_2-国外资源加速\",\"children\":[]},{\"level\":3,\"title\":\"3. 特殊命令的加速\",\"slug\":\"_3-特殊命令的加速\",\"link\":\"#_3-特殊命令的加速\",\"children\":[]},{\"level\":3,\"title\":\"4. 通用的简便的配置方法\",\"slug\":\"_4-通用的简便的配置方法\",\"link\":\"#_4-通用的简便的配置方法\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.29,\"words\":688},\"filePathRelative\":\"GPUdocs/user/fast/network.md\",\"localizedDate\":\"2023年8月31日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
