export const data = JSON.parse("{\"key\":\"v-75075d3a\",\"path\":\"/GPUdocs/user/fast.html\",\"title\":\"快速开始\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"快速开始\",\"icon\":\"more\",\"order\":1,\"author\":\"fengjk\",\"date\":\"2023-06-14T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"使用技巧\",\"快速开始\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"前言 这是一个快速使用文档，会略去很多功能和细节，更多功能和方法可以参考详细文档 (../../GPUdocs) 一、 登入服务器 在你申请算力之后，管理员会给你容器的IP、端口、账号、密码，其中IP一般为我们的域名位置.liandanlu.cn，账号为root。 获得账密之后，你需要使用Xshell、xterm等软件连接，设置正确端口和账密之后就可以...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/GPUdocs/user/fast.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"快速开始\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"前言 这是一个快速使用文档，会略去很多功能和细节，更多功能和方法可以参考详细文档 (../../GPUdocs) 一、 登入服务器 在你申请算力之后，管理员会给你容器的IP、端口、账号、密码，其中IP一般为我们的域名位置.liandanlu.cn，账号为root。 获得账密之后，你需要使用Xshell、xterm等软件连接，设置正确端口和账密之后就可以...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"http://liandan.cn:8080/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"快速开始\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"使用技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"快速开始\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-06-14T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"快速开始\\\",\\\"image\\\":[\\\"http://liandan.cn:8080/\\\"],\\\"datePublished\\\":\\\"2023-06-14T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"一、 登入服务器\",\"slug\":\"一、-登入服务器\",\"link\":\"#一、-登入服务器\",\"children\":[]},{\"level\":2,\"title\":\"二、 使用说明\",\"slug\":\"二、-使用说明\",\"link\":\"#二、-使用说明\",\"children\":[{\"level\":3,\"title\":\"GPU分配原则\",\"slug\":\"gpu分配原则\",\"link\":\"#gpu分配原则\",\"children\":[]}]},{\"level\":2,\"title\":\"三、 注意事项\",\"slug\":\"三、-注意事项\",\"link\":\"#三、-注意事项\",\"children\":[]},{\"level\":2,\"title\":\"四、 使用建议\",\"slug\":\"四、-使用建议\",\"link\":\"#四、-使用建议\",\"children\":[]}],\"readingTime\":{\"minutes\":4.72,\"words\":1416},\"filePathRelative\":\"GPUdocs/user/fast.md\",\"localizedDate\":\"2023年6月14日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
