export const data = JSON.parse("{\"key\":\"v-709c54dc\",\"path\":\"/GPUdocs/user/nas.html\",\"title\":\"简略的NAS使用方式（GPU服务器内）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"简略的NAS使用方式（GPU服务器内）\",\"icon\":\"page\",\"order\":1,\"author\":\"fengjk\",\"date\":\"2023-06-18T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"使用技巧\",\"NAS存储\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"前言 我们的集群的整体设计理念是存算分离，数据共享。因此使用NAS作为核心存储设备，GPU服务器只是作为计算使用。 使用NAS存储技术可以增加每个人的存储空间、同步多机之间的数据、降低存储成本、降低坏盘风险。NAS存储设计理念 外部存储，存储设备和计算设备（GPU）分离，不在同一台机器上。NAS的空间很大（至少20T以上）。 在GPU服务器上的提现就是...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/GPUdocs/user/nas.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"简略的NAS使用方式（GPU服务器内）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"前言 我们的集群的整体设计理念是存算分离，数据共享。因此使用NAS作为核心存储设备，GPU服务器只是作为计算使用。 使用NAS存储技术可以增加每个人的存储空间、同步多机之间的数据、降低存储成本、降低坏盘风险。NAS存储设计理念 外部存储，存储设备和计算设备（GPU）分离，不在同一台机器上。NAS的空间很大（至少20T以上）。 在GPU服务器上的提现就是...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"http://liandan.cn:8080/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"简略的NAS使用方式（GPU服务器内）\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"使用技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"NAS存储\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-06-18T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"简略的NAS使用方式（GPU服务器内）\\\",\\\"image\\\":[\\\"http://liandan.cn:8080/\\\"],\\\"datePublished\\\":\\\"2023-06-18T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"一、 GPU服务器上的使用方式\",\"slug\":\"一、-gpu服务器上的使用方式\",\"link\":\"#一、-gpu服务器上的使用方式\",\"children\":[{\"level\":3,\"title\":\"1. 使用建议\",\"slug\":\"_1-使用建议\",\"link\":\"#_1-使用建议\",\"children\":[]},{\"level\":3,\"title\":\"2. NAS目录在容器内的位置\",\"slug\":\"_2-nas目录在容器内的位置\",\"link\":\"#_2-nas目录在容器内的位置\",\"children\":[]}]},{\"level\":2,\"title\":\"二、 本地Windows上的使用方式\",\"slug\":\"二、-本地windows上的使用方式\",\"link\":\"#二、-本地windows上的使用方式\",\"children\":[]}],\"readingTime\":{\"minutes\":3.43,\"words\":1030},\"filePathRelative\":\"GPUdocs/user/nas.md\",\"localizedDate\":\"2023年6月18日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
