export const data = JSON.parse("{\"key\":\"v-6487d30e\",\"path\":\"/GPUdocs/user/network.html\",\"title\":\"服务器网络配置、翻墙、国外资源加速\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"服务器网络配置、翻墙、国外资源加速\",\"icon\":\"page\",\"order\":1,\"author\":\"fengjk\",\"date\":\"2023-06-14T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"使用技巧\",\"网络\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"前言 魔法上网所使用的的原理是代理，即通过https加密让代理服务器代为请求所需国外资源以加速访问，可以在Project V (https://www.v2fly.org/)中了解更多。目前的代理服务器为服务器管理员搭建。 代理地址和命令可能会发生变化，请关注文档变更和管理员通知。 链数服务器网络 1. 国内资源访问 链数机器可以自由访问国内网站，如g...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/GPUdocs/user/network.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"服务器网络配置、翻墙、国外资源加速\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"前言 魔法上网所使用的的原理是代理，即通过https加密让代理服务器代为请求所需国外资源以加速访问，可以在Project V (https://www.v2fly.org/)中了解更多。目前的代理服务器为服务器管理员搭建。 代理地址和命令可能会发生变化，请关注文档变更和管理员通知。 链数服务器网络 1. 国内资源访问 链数机器可以自由访问国内网站，如g...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"http://liandan.cn:8080/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"服务器网络配置、翻墙、国外资源加速\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"使用技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"网络\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-06-14T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"服务器网络配置、翻墙、国外资源加速\\\",\\\"image\\\":[\\\"http://liandan.cn:8080/\\\"],\\\"datePublished\\\":\\\"2023-06-14T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"前言\",\"slug\":\"前言\",\"link\":\"#前言\",\"children\":[]},{\"level\":2,\"title\":\"链数服务器网络\",\"slug\":\"链数服务器网络\",\"link\":\"#链数服务器网络\",\"children\":[{\"level\":3,\"title\":\"1. 国内资源访问\",\"slug\":\"_1-国内资源访问\",\"link\":\"#_1-国内资源访问\",\"children\":[]},{\"level\":3,\"title\":\"2. 国外资源加速（pip， git clone，apt等）\",\"slug\":\"_2-国外资源加速-pip-git-clone-apt等\",\"link\":\"#_2-国外资源加速-pip-git-clone-apt等\",\"children\":[]},{\"level\":3,\"title\":\"3. 网盘/外网资源下载\",\"slug\":\"_3-网盘-外网资源下载\",\"link\":\"#_3-网盘-外网资源下载\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.75,\"words\":1125},\"filePathRelative\":\"GPUdocs/user/network.md\",\"localizedDate\":\"2023年6月14日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
