export const data = JSON.parse("{\"key\":\"v-efbfe19a\",\"path\":\"/Userdocs/fast/login.html\",\"title\":\"登录\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"登录\",\"icon\":\"user-plus\",\"order\":1,\"author\":\"fengjk\",\"date\":\"2023-08-31T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"使用技巧\",\"快速开始\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"前言 这是一个快速使用说明，会略去很多功能和细节，更多功能请阅读全部用户手册。 登入服务器 申请算力之后，管理员会给你容器的IP、端口、账号、密码， IP一般为域名位置.liandanlu.cn，账号为root。 获得账密之后，你需要使用Xshell、xterm等软件连接，设置正确端口和账密之后就可以通过ssh协议连接进入容器系统，容器系统默认为Ubu...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/Userdocs/fast/login.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"登录\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"前言 这是一个快速使用说明，会略去很多功能和细节，更多功能请阅读全部用户手册。 登入服务器 申请算力之后，管理员会给你容器的IP、端口、账号、密码， IP一般为域名位置.liandanlu.cn，账号为root。 获得账密之后，你需要使用Xshell、xterm等软件连接，设置正确端口和账密之后就可以通过ssh协议连接进入容器系统，容器系统默认为Ubu...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"http://liandan.cn:8080/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"登录\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"使用技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"快速开始\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-08-31T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"登录\\\",\\\"image\\\":[\\\"http://liandan.cn:8080/\\\"],\\\"datePublished\\\":\\\"2023-08-31T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"登入服务器\",\"slug\":\"登入服务器\",\"link\":\"#登入服务器\",\"children\":[]},{\"level\":2,\"title\":\"注意事项\",\"slug\":\"注意事项\",\"link\":\"#注意事项\",\"children\":[]},{\"level\":2,\"title\":\"使用建议\",\"slug\":\"使用建议\",\"link\":\"#使用建议\",\"children\":[]}],\"readingTime\":{\"minutes\":3.29,\"words\":987},\"filePathRelative\":\"Userdocs/fast/login.md\",\"localizedDate\":\"2023年8月31日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
