export const data = JSON.parse("{\"key\":\"v-38911ace\",\"path\":\"/Userdocs/fast/network.html\",\"title\":\"容器网络配置\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"容器网络配置\",\"icon\":\"network-wired\",\"order\":2,\"author\":\"fengjk\",\"date\":\"2023-08-31T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"使用技巧\",\"快速开始\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"两地网络状况 链数服务器 链数服务器可以直接上网，但是对于安装国外软件较慢的情况，我们提供了一些解决方案，通过代理加速外国资源访问。 校内服务器 校内服务器无法直接上网，只能正确配置代理之后才能上网。 本文的很多内容和上一节 (./environment.md)重叠，本文给出了一些解释和更简便的方法。 我们使用上网方式，称为“代理”或者“代理上网”。 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/Userdocs/fast/network.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"容器网络配置\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"两地网络状况 链数服务器 链数服务器可以直接上网，但是对于安装国外软件较慢的情况，我们提供了一些解决方案，通过代理加速外国资源访问。 校内服务器 校内服务器无法直接上网，只能正确配置代理之后才能上网。 本文的很多内容和上一节 (./environment.md)重叠，本文给出了一些解释和更简便的方法。 我们使用上网方式，称为“代理”或者“代理上网”。 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"http://liandan.cn:8080/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"容器网络配置\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"使用技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"快速开始\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-08-31T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"容器网络配置\\\",\\\"image\\\":[\\\"http://liandan.cn:8080/\\\"],\\\"datePublished\\\":\\\"2023-08-31T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"两地网络状况\",\"slug\":\"两地网络状况\",\"link\":\"#两地网络状况\",\"children\":[]},{\"level\":2,\"title\":\"通用的简便的配置方法\",\"slug\":\"通用的简便的配置方法\",\"link\":\"#通用的简便的配置方法\",\"children\":[]},{\"level\":2,\"title\":\"使用代理时的问题说明\",\"slug\":\"使用代理时的问题说明\",\"link\":\"#使用代理时的问题说明\",\"children\":[]}],\"readingTime\":{\"minutes\":3.93,\"words\":1179},\"filePathRelative\":\"Userdocs/fast/network.md\",\"localizedDate\":\"2023年8月31日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
