export const data = JSON.parse("{\"key\":\"v-5359768a\",\"path\":\"/GPUdocs/user/nas/show.html\",\"title\":\"功能展示集锦\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"功能展示集锦\",\"icon\":\"eye\",\"order\":1,\"author\":\"fengjk\",\"date\":\"2023-09-01T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"使用技巧\",\"NAS存储\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"网页在线观看视频 可以流畅在线观看nas中的图片、视频。 使用浏览器在线共享视频 多端同步 手机、电脑、服务器均可以连接上nas，他们的数据是相通的。 相当于实验室的云盘系统，可以用来备份文件、同步数据。 服务器和Windows的数据相同 离线下载 在下载机上挂上下载程序即可，可以24h下载。 等下载完成之后拖入NAS即可。 服务器和Windows的数...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/GPUdocs/user/nas/show.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"功能展示集锦\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"网页在线观看视频 可以流畅在线观看nas中的图片、视频。 使用浏览器在线共享视频 多端同步 手机、电脑、服务器均可以连接上nas，他们的数据是相通的。 相当于实验室的云盘系统，可以用来备份文件、同步数据。 服务器和Windows的数据相同 离线下载 在下载机上挂上下载程序即可，可以24h下载。 等下载完成之后拖入NAS即可。 服务器和Windows的数...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"http://liandan.cn:8080/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"功能展示集锦\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"使用技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"NAS存储\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-09-01T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"功能展示集锦\\\",\\\"image\\\":[\\\"http://liandan.cn:8080/\\\"],\\\"datePublished\\\":\\\"2023-09-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"网页在线观看视频\",\"slug\":\"网页在线观看视频\",\"link\":\"#网页在线观看视频\",\"children\":[]},{\"level\":2,\"title\":\"多端同步\",\"slug\":\"多端同步\",\"link\":\"#多端同步\",\"children\":[]},{\"level\":2,\"title\":\"离线下载\",\"slug\":\"离线下载\",\"link\":\"#离线下载\",\"children\":[]},{\"level\":2,\"title\":\"浏览日志\",\"slug\":\"浏览日志\",\"link\":\"#浏览日志\",\"children\":[]},{\"level\":2,\"title\":\"分享链接\",\"slug\":\"分享链接\",\"link\":\"#分享链接\",\"children\":[]}],\"readingTime\":{\"minutes\":0.93,\"words\":280},\"filePathRelative\":\"GPUdocs/user/nas/show.md\",\"localizedDate\":\"2023年9月1日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
