export const data = JSON.parse("{\"key\":\"v-65c31295\",\"path\":\"/GPUdocs/deploy/newuser.html\",\"title\":\"如何添加一个新的用户容器\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"如何添加一个新的用户容器\",\"icon\":\"page\",\"order\":1,\"author\":\"fengjk\",\"date\":\"2023-06-23T00:00:00.000Z\",\"category\":[\"GPU服务器文档\"],\"tag\":[\"服务器部署\",\"GPU服务器\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"一、 导入模板容器 将之前保存的压缩包导入到镜像中，并且别名称为template。- 初始化用户实例。生成一个名为mars-huanghansheng的容器; 二、 用户容器配置 1. 密码修改 修改用户root密码; 按照正规的编码方式将每个人的密码进行修改，并且需要是强密码，因为nas数据是直连容器的。 一般不会为了数据安全，每个人设置不同的密码。...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/GPUdocs/deploy/newuser.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"如何添加一个新的用户容器\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"一、 导入模板容器 将之前保存的压缩包导入到镜像中，并且别名称为template。- 初始化用户实例。生成一个名为mars-huanghansheng的容器; 二、 用户容器配置 1. 密码修改 修改用户root密码; 按照正规的编码方式将每个人的密码进行修改，并且需要是强密码，因为nas数据是直连容器的。 一般不会为了数据安全，每个人设置不同的密码。...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fengjk\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"服务器部署\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GPU服务器\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-06-23T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"如何添加一个新的用户容器\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-06-23T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fengjk\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、 导入模板容器\",\"slug\":\"一、-导入模板容器\",\"link\":\"#一、-导入模板容器\",\"children\":[]},{\"level\":2,\"title\":\"二、 用户容器配置\",\"slug\":\"二、-用户容器配置\",\"link\":\"#二、-用户容器配置\",\"children\":[{\"level\":3,\"title\":\"1. 密码修改\",\"slug\":\"_1-密码修改\",\"link\":\"#_1-密码修改\",\"children\":[]},{\"level\":3,\"title\":\"2. 配置文件修改、设备添加\",\"slug\":\"_2-配置文件修改、设备添加\",\"link\":\"#_2-配置文件修改、设备添加\",\"children\":[]},{\"level\":3,\"title\":\"3. 给容器加入CPU,内存限制\",\"slug\":\"_3-给容器加入cpu-内存限制\",\"link\":\"#_3-给容器加入cpu-内存限制\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.74,\"words\":821},\"filePathRelative\":\"GPUdocs/deploy/newuser.md\",\"localizedDate\":\"2023年6月23日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
