export const data = JSON.parse("{\"key\":\"v-7b941492\",\"path\":\"/NAS%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.html\",\"title\":\"NAS实验室用户手册\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"NAS：网络附加存储设备，就是一个网盘，不过更加方便与快速，可以直接挂载在电脑内，当做本地磁盘使用。 前言 你还在为云盘速度拉胯而苦恼吗？ 你还在为实验数据过大而焦躁吗？ 你还在为多台电脑数据不容易同步而哭泣吗？ 还在为百度云账号数量限制而寻求验证码吗？ 还在和同学使用QQ传递文件吗？ 那就来使用实验室NAS吧，方便快捷，量大管饱。 !!!exampl...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/NAS%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Docs Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"NAS实验室用户手册\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"NAS：网络附加存储设备，就是一个网盘，不过更加方便与快速，可以直接挂载在电脑内，当做本地磁盘使用。 前言 你还在为云盘速度拉胯而苦恼吗？ 你还在为实验数据过大而焦躁吗？ 你还在为多台电脑数据不容易同步而哭泣吗？ 还在为百度云账号数量限制而寻求验证码吗？ 还在和同学使用QQ传递文件吗？ 那就来使用实验室NAS吧，方便快捷，量大管饱。 !!!exampl...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"NAS实验室用户手册\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"NAS实验室用户手册\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、 使用方法\",\"slug\":\"一、-使用方法\",\"link\":\"#一、-使用方法\",\"children\":[{\"level\":3,\"title\":\"1. 不同网络条件下的使用\",\"slug\":\"_1-不同网络条件下的使用\",\"link\":\"#_1-不同网络条件下的使用\",\"children\":[]},{\"level\":3,\"title\":\"2. 文件目录说明\",\"slug\":\"_2-文件目录说明\",\"link\":\"#_2-文件目录说明\",\"children\":[]},{\"level\":3,\"title\":\"3. windows10上的高级操作\",\"slug\":\"_3-windows10上的高级操作\",\"link\":\"#_3-windows10上的高级操作\",\"children\":[]},{\"level\":3,\"title\":\"4. 云盘资料下载到NAS中\",\"slug\":\"_4-云盘资料下载到nas中\",\"link\":\"#_4-云盘资料下载到nas中\",\"children\":[]},{\"level\":3,\"title\":\"x. GPU服务器连接NAS //ToDo 在做了在做了\",\"slug\":\"x-gpu服务器连接nas-todo-在做了在做了\",\"link\":\"#x-gpu服务器连接nas-todo-在做了在做了\",\"children\":[]},{\"level\":3,\"title\":\"10. 连接速度（上传下载速度）\",\"slug\":\"_10-连接速度-上传下载速度\",\"link\":\"#_10-连接速度-上传下载速度\",\"children\":[]},{\"level\":3,\"title\":\"内测注意事项\",\"slug\":\"内测注意事项\",\"link\":\"#内测注意事项\",\"children\":[]}]},{\"level\":2,\"title\":\"ToDo List\",\"slug\":\"todo-list\",\"link\":\"#todo-list\",\"children\":[]},{\"level\":2,\"title\":\"目前内测用户\",\"slug\":\"目前内测用户\",\"link\":\"#目前内测用户\",\"children\":[]}],\"readingTime\":{\"minutes\":4.11,\"words\":1232},\"filePathRelative\":\"NAS文档/使用文档/使用文档.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
