export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"炼丹炉系统\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"icon\":\"home\",\"title\":\"炼丹炉系统\",\"heroImage\":\"/logo.jpg\",\"heroText\":\"炼丹炉\",\"tagline\":\"一个先进的多机多GPU管理方案\",\"actions\":[{\"text\":\"快速开始💡\",\"link\":\"/Userdocs/fast/login\",\"type\":\"primary\"},{\"text\":\"AList网页🔑\",\"link\":\"linkdata.liandanlu.cn:40000\",\"type\":\"secondary\"},{\"text\":\"未来计划\",\"link\":\"/overview/\"},{\"text\":\"管理员文档🐠\",\"link\":\"/GPUdocs/\"}],\"features\":[{\"title\":\"容器管理\",\"icon\":\"/assets/icon/容器.svg\",\"details\":\"以Linux容器为基础，管理各个用户空间，实现环境隔离与资源控制\",\"link\":\"/Userdocs/fast/container.md\"},{\"title\":\"NAS同步\",\"icon\":\"/assets/icon/NAS设备.svg\",\"details\":\"建立万兆核心NAS，每台机器与NAS互联，实现全局数据共享与超大存储空间\",\"link\":\"/Userdocs/nas/whatis.md\"},{\"title\":\"高密集群\",\"icon\":\"/assets/icon/服务器.svg\",\"details\":\"使用可支持8卡的GPU准系统组建每一台服务器，提高服务器的计算密度，减少机房空间浪费\",\"link\":\"/overview/README.md\"},{\"title\":\"便宜实惠\",\"icon\":\"/assets/icon/人民币.svg\",\"details\":\"以自建服务器准系统为基础，搭建所有的服务集群，价格压缩到最低，同时性能上也不逊色于高贵的成品方案，把钱花在刀刃上。\",\"link\":\"/overview/gpu.md\"},{\"title\":\"在做了在做了\",\"icon\":\"/assets/icon/更多.svg\",\"details\":\"别问，问就是bug在修，新功能会出，文档开始写了\",\"link\":\"/overview/\"}],\"copyright\":false,\"footer\":\"Theme by <a href=\\\"https://theme-hope.vuejs.press/\\\" target=\\\"_blank\\\">VuePress Theme Hope</a> | MIT Licensed, Copyright © 2019-present Mr.Hope\",\"description\":\"项目内容 你还在为云盘速度拉胯而苦恼吗？你还在为多台服务器数据、代码不同步而焦躁吗？你还在为管理员不给你sudo权限而哭泣吗？还在为资金不足而心烦吗？ 炼丹炉系统都能解决你的问题 系统简述 本系统以NAS为核心文件存储存储器，所有GPU服务器都会与NAS进行万兆高速连接，从而实现所有服务器间的文件全互联。 所有服务器可以共同连接、访问、修改NAS上自己...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://liandan.cn:8080/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"炼丹炉系统\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"项目内容 你还在为云盘速度拉胯而苦恼吗？你还在为多台服务器数据、代码不同步而焦躁吗？你还在为管理员不给你sudo权限而哭泣吗？还在为资金不足而心烦吗？ 炼丹炉系统都能解决你的问题 系统简述 本系统以NAS为核心文件存储存储器，所有GPU服务器都会与NAS进行万兆高速连接，从而实现所有服务器间的文件全互联。 所有服务器可以共同连接、访问、修改NAS上自己...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"炼丹炉系统\\\",\\\"description\\\":\\\"项目内容 你还在为云盘速度拉胯而苦恼吗？你还在为多台服务器数据、代码不同步而焦躁吗？你还在为管理员不给你sudo权限而哭泣吗？还在为资金不足而心烦吗？ 炼丹炉系统都能解决你的问题 系统简述 本系统以NAS为核心文件存储存储器，所有GPU服务器都会与NAS进行万兆高速连接，从而实现所有服务器间的文件全互联。 所有服务器可以共同连接、访问、修改NAS上自己...\\\"}\"]]},\"headers\":[{\"level\":2,\"title\":\"项目内容\",\"slug\":\"项目内容\",\"link\":\"#项目内容\",\"children\":[]},{\"level\":2,\"title\":\"项目目的\",\"slug\":\"项目目的\",\"link\":\"#项目目的\",\"children\":[]}],\"readingTime\":{\"minutes\":2.97,\"words\":892},\"filePathRelative\":\"README.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
