export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"炼丹炉系统","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-76601b7e","/GPUdocs/",{"y":"a","t":"GPU服务器文档","i":"computer","I":0},["/GPUdocs/index.html","/GPUdocs/README.md"]],
  ["v-7f11024d","/NASdocs/",{"y":"a","t":"NAS文档","i":"creative","I":0},["/NASdocs/index.html","/NASdocs/README.md"]],
  ["v-5c0dd206","/overview/",{"y":"a","t":"炼丹炉系统整体设计蓝图","i":"list-ol","O":1},["/overview/index.html","/overview/README.md"]],
  ["v-264ff4ac","/overview/gpu.html",{"y":"a","t":"GPU分封图","i":"computer","O":1},["/overview/gpu","/overview/gpu.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","t":"项目主页","i":"home"},["/zh/index.html","/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"y":"s","t":"幻灯片页","i":"slides"},["/zh/slides","/zh/slides.md"]],
  ["v-9a6cd902","/GPUdocs/deploy/container.html",{"y":"a","t":"如何配置模板容器、迁移用户容器","i":"truck-moving","O":1},["/GPUdocs/deploy/container","/GPUdocs/deploy/container.md"]],
  ["v-8e6b356c","/GPUdocs/deploy/host.html",{"y":"a","t":"如何配置新物理机系统","i":"computer","O":1},["/GPUdocs/deploy/host","/GPUdocs/deploy/host.md"]],
  ["v-65c31295","/GPUdocs/deploy/newuser.html",{"y":"a","t":"如何添加一个新的用户容器","i":"user-plus","O":1},["/GPUdocs/deploy/newuser","/GPUdocs/deploy/newuser.md"]],
  ["v-4ee8dc23","/GPUdocs/user/",{"y":"a","t":"如何使用GPU服务器","i":"page","O":1},["/GPUdocs/user/index.html","/GPUdocs/user/README.md"]],
  ["v-78abfa1b","/GPUdocs/user/acc.html",{"y":"a","t":"程序优化与加速","i":"code","O":1},["/GPUdocs/user/acc","/GPUdocs/user/acc.md"]],
  ["v-75075d3a","/GPUdocs/user/fast.html",{"y":"a","t":"快速开始","O":1},["/GPUdocs/user/fast","/GPUdocs/user/fast.md"]],
  ["v-709c54dc","/GPUdocs/user/nas.html",{"y":"a","t":"NAS使用(服务器向)","i":"page","O":1},["/GPUdocs/user/nas","/GPUdocs/user/nas.md"]],
  ["v-6487d30e","/GPUdocs/user/network.html",{"y":"a","t":"国外资源加速、网络配置","i":"network","O":1},["/GPUdocs/user/network","/GPUdocs/user/network.md"]],
  ["v-0cee2d8a","/NASdocs/deploy/",{"y":"a","t":"NAS部署的细节文档"},["/NASdocs/deploy/index.html","/NASdocs/deploy/README.md"]],
  ["v-399d7f52","/NASdocs/maintain/",{"y":"a","t":"NAS日常维护","i":"config","O":2},["/NASdocs/maintain/index.html","/NASdocs/maintain/README.md"]],
  ["v-374bf397","/NASdocs/user/",{"y":"a","t":"如何使用NAS","i":"page","O":1},["/NASdocs/user/index.html","/NASdocs/user/README.md"]],
  ["v-1856579b","/Userdocs/fast/container.html",{"y":"a","t":"容器分配方式","O":2},["/Userdocs/fast/container","/Userdocs/fast/container.md"]],
  ["v-3abd0089","/Userdocs/fast/environment.html",{"y":"a","t":"安装计算环境","i":"bug","O":1},["/Userdocs/fast/environment","/Userdocs/fast/environment.md"]],
  ["v-3b8c6466","/Userdocs/fast/faq.html",{"y":"a","t":"FAQ","i":"question","O":1},["/Userdocs/fast/faq","/Userdocs/fast/faq.md"]],
  ["v-efbfe19a","/Userdocs/fast/login.html",{"y":"a","t":"登录","i":"user-plus","O":1},["/Userdocs/fast/login","/Userdocs/fast/login.md"]],
  ["v-38911ace","/Userdocs/fast/network.html",{"y":"a","t":"容器网络配置","i":"network-wired","O":2},["/Userdocs/fast/network","/Userdocs/fast/network.md"]],
  ["v-704f6579","/Userdocs/nas/alist.html",{"y":"a","t":"AList网页","i":"wifi","O":1},["/Userdocs/nas/alist","/Userdocs/nas/alist.md"]],
  ["v-1619fb32","/Userdocs/nas/download.html",{"y":"a","t":"下载数据集","i":"download","O":1},["/Userdocs/nas/download","/Userdocs/nas/download.md"]],
  ["v-769cf21f","/Userdocs/nas/mount.html",{"y":"a","t":"NAS的使用","O":1},["/Userdocs/nas/mount","/Userdocs/nas/mount.md"]],
  ["v-0ec57b46","/Userdocs/nas/show.html",{"y":"a","t":"功能展示集锦","i":"eye","O":1},["/Userdocs/nas/show","/Userdocs/nas/show.md"]],
  ["v-f3007e68","/Userdocs/nas/whatis.html",{"y":"a","t":"NAS是什么","O":1},["/Userdocs/nas/whatis","/Userdocs/nas/whatis.md"]],
  ["v-05a51f0d","/blog/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/zfs%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F.html",{"y":"a","t":"zfs文件系统简介","i":"page","O":1},["/blog/操作系统/zfs文件系统.html","/blog/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/zfs%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F","/blog/操作系统/zfs文件系统.md","/blog/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/zfs%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F.md"]],
  ["v-7854d450","/blog/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/v2ray%E6%8A%80%E6%9C%AF.html",{"y":"a","t":""},["/blog/计算机网络/v2ray技术.html","/blog/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/v2ray%E6%8A%80%E6%9C%AF","/blog/计算机网络/v2ray技术.md","/blog/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/v2ray%E6%8A%80%E6%9C%AF.md"]],
  ["v-2b64e284","/zh/demo/",{"y":"a","t":"主要功能与配置演示","i":"discover","I":0},["/zh/demo/index.html","/zh/demo/README.md"]],
  ["v-c1942916","/zh/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"config","O":3},["/zh/demo/disable","/zh/demo/disable.md"]],
  ["v-65c00218","/zh/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},["/zh/demo/encrypt","/zh/demo/encrypt.md"]],
  ["v-36295574","/zh/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"markdown","O":2},["/zh/demo/markdown","/zh/demo/markdown.md"]],
  ["v-62ced1a6","/zh/demo/page.html",{"y":"a","t":"页面配置","i":"page","O":1},["/zh/demo/page","/zh/demo/page.md"]],
  ["v-47357bdb","/zh/guide/",{"y":"a","t":"指南","i":"creative"},["/zh/guide/index.html","/zh/guide/README.md"]],
  ["v-763c1cd7","/zh/guide/bar/",{"y":"a","t":"Bar 功能","i":"creative"},["/zh/guide/bar/index.html","/zh/guide/bar/README.md"]],
  ["v-1e317375","/zh/guide/bar/baz.html",{"y":"a","t":"Baz","i":"info"},["/zh/guide/bar/baz","/zh/guide/bar/baz.md"]],
  ["v-763e2284","/zh/guide/foo/",{"y":"a","t":"Foo 功能","i":"config"},["/zh/guide/foo/index.html","/zh/guide/foo/README.md"]],
  ["v-00fb7173","/zh/guide/foo/ray.html",{"y":"a","t":"Ray","i":"config"},["/zh/guide/foo/ray","/zh/guide/foo/ray.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-c4e44272","/GPUdocs/deploy/",{"y":"p","t":"Deploy"},["/GPUdocs/deploy/index.html"]],
  ["v-a260783a","/Userdocs/fast/",{"y":"p","t":"Fast"},["/Userdocs/fast/index.html"]],
  ["v-eb315520","/Userdocs/",{"y":"p","t":"Userdocs"},["/Userdocs/index.html"]],
  ["v-99dacf02","/Userdocs/nas/",{"y":"p","t":"Nas"},["/Userdocs/nas/index.html"]],
  ["v-7778b26e","/blog/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/",{"y":"p","t":"操作系统"},["/blog/操作系统/","/blog/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/index.html"]],
  ["v-145ac574","/blog/",{"y":"p","t":"Blog"},["/blog/index.html"]],
  ["v-5eedb31e","/blog/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/",{"y":"p","t":"计算机网络"},["/blog/计算机网络/","/blog/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/index.html"]],
]
